import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const {
    data: characterPair,
    refetch,
    isLoading,
  } = trpc.getCharacter.getPair.useQuery();

  const voteMutation = trpc.getVotes.castVote.useMutation();

  const voteForRoundest = (selected: number) => {
    if (!characterPair) return; // Early escape to make Typescript happy

    if (selected === characterPair?.firstCharacter?.id) {
      voteMutation.mutate({
        votedFor: characterPair.firstCharacter.id,
        votedAgainst: characterPair.secondCharacter!.id,
      });
    } else {
      // else fire voteFor with second ID
      voteMutation.mutate({
        votedFor: characterPair.secondCharacter!.id,
        votedAgainst: characterPair.firstCharacter!.id,
      });
    }
    refetch();
  };

  const fetchingNext = voteMutation.isLoading || isLoading;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-900 text-gray-100">
        <h1 className="text-center text-3xl">
          Who is coolest anime character?{" "}
        </h1>
        {characterPair && (
          <div className="mt-10 flex gap-5 items-center justify-between border-2 border-emerald-700 p-20">
            <PokemonListing
              character={characterPair.firstCharacter}
              vote={() => voteForRoundest(characterPair.firstCharacter!.id)}
              disabled={fetchingNext}
            />
            <div className="p-8 text-xl italic">{"or"}</div>
            <PokemonListing
              character={characterPair.secondCharacter}
              vote={() => voteForRoundest(characterPair.secondCharacter!.id)}
              disabled={fetchingNext}
            />
          </div>
        )}

        <Link href={`/results`} className="text-lg mt-5">Results</Link>
      </main>
    </>
  );
};

const PokemonListing: React.FC<{
  character: any;
  vote: () => void;
  disabled: boolean;
}> = (props) => {
  return (
    <div
      className={`flex flex-col items-center transition-opacity ${
        props.disabled && "opacity-0"
      }`}
      key={props.character.id}
    >
      <div className="mt-[-0.5rem] text-center font-medium text-xl capitalize">
        {props.character.name}
      </div>
      <Image
        src={props.character.imageUrl}
        width={256}
        height={256}
        layout="fixed"
        className="animate-fade-in mt-5 rounded-lg"
        alt="character"
      />
      <button
        className={`mt-5 w-32 rounded-lg bg-emerald-600 px-3 py-2 font-medium`}
        onClick={() => props.vote()}
        disabled={props.disabled}
      >
        Cooler
      </button>
    </div>
  );
};

export default Home;
